name: Continuous Integration (CI)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres_testing
          POSTGRES_PASSWORD: pg_testing_pass
          POSTGRES_DB: forumapitest_db

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: DB Migration and Automation Testing
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          HOST: localhost
          PORT: 3000
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres_testing
          PGPASSWORD: pg_testing_pass
          PGDATABASE: forumapitest_db
          ACCESS_TOKEN_KEY: sangat_rahasia
          REFRESH_TOKEN_KEY: rahasia_sangat
          ACCESS_TOKEN_AGE: 3600
